version: '3'
networks:
  bookReview_network:
    driver: bridge

services:
  bookReview_postgres:
    image: "postgres:15.1"
    container_name: bookReview-postgres
    environment:
      - POSTGRES_PASSWORD=bookreview
      - POSTGRES_USER=bookreview
      - POSTGRES_DB=bookreview
    ports:
      - "5432:5432"
    volumes:
      - bookReview_postgresql_vol:/var/lib/postgresql/data
    networks:
      bookReview_network:
        aliases:
          - postgres

volumes:
  bookReview_postgresql_vol: